config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users do
    resources :foods
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :foods
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def calories_total
    foods = self.foods
    calories = 0
    foods.each do |food|
      calories = calories + food.calories
    end
    calories
  end

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user =  User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @food = @user.foods.new
  end

  def create
    @user = User.find(params[:user_id])
    @food = @user.foods.new(food_params)

    @food.save
    @calories_total = @user.calories_total
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @food = @user.foods.find(params[:id])
    @food.destroy
    redirect_to user_path(@user)
  end

  private
  def food_params
    params.require(:food).permit(:name, :calories, :details, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:username]. params[:password])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      session[:user_id] = 0
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    session[:user_id] ||= 1
  end

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
    foods = @user.foods.all
    @calories = 0       ##I eventually want this to be computed at the model level
    foods.each do |food| ## Having trouble, using this as hold-over for now.
      @calories = @calories + food.calories
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_foodtile.html.erb
<%= link_to '[x]', user_food_path(@user, @food),  method: 'delete' %> <%= @food.name %>(<%= @food.calories %> cal.) -- <%= @food.details %>

app/views/foods/_form.html.erb
<%= form_for [@user, @food], remote:true do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :calories %>
  <%= f.number_field :calories %><br>

  <%= f.label :details %>
  <%= f.text_field :details %><br>

  <%= f.submit %>
<% end %>

app/views/foods/create.js.erb
$('#new_food').remove();
$('#add_food_link').show();
$('#food_list').append('<li><%= j render "foodtile", locals:{ :@food => params[:food]} %></li>');
$('#calorie_count').html('<%=  @calories_total %>');

app/views/foods/new.html.erb
<%= render 'form' %>

app/views/foods/new.js.erb
$('#add_food_link').hide().after('<%= j render "form" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <h1><%= link_to "Health Tracker", root_path %></h1>
    <hr>
      <%= User.find(session[:user_id]).username %>
      <%= link_to 'Sign Up', login_path %>
      <%= link_to 'Sign Out', logout_path, method: 'get' %>
    <hr>
  </nav>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
HI!<br>
<% @users.each do |user| %>
  <%=link_to user.username, user_path(user) %> -- <%= user.email %>
<% end %>
<br>

app/views/users/show.html.erb
Now Showing: <br> <hr>
<p>
<h2><%= @user.username %></h2> <br>
<h5><%= @user.email %></h5>
</p>
<hr>
<h3><u>FOODS:</u><h3>
  <ul id="food_list">
    <% if @user.foods.any? %>
      <% @user.foods.each do |food| %>
        <li>
          <%= link_to '[x]', user_food_path(@user, food),  method: 'delete' %> <%= food.name %> (<%= food.calories %> calories)
        </li>
      <% end %>
    <% end %>
  </ul>
  Total Calories: <div id="calorie_count"><%= @user.calories_total %></div>
  <%= link_to "Add Food", new_user_food_path(@user), id:'add_food_link', remote: true %>